### ISSUE TITLE
Escape all the shell things!

### ISSUE THREAD

**Issue by assertchris** [asyncphp/doorman#1]
https://twitter.com/asgrim/status/620474794685898752

**Comment by asgrim** [comment]
:D

**Comment by assertchris** [comment]
@asgrim: how about something like this?

https://github.com/asyncphp/doorman/blob/cff6addf82e98ec926cfb0d7e1c7d9b6fa53d2f4/src/Shell/BashShell.php#L19-L27

Uses:

https://github.com/asyncphp/doorman/blob/cff6addf82e98ec926cfb0d7e1c7d9b6fa53d2f4/src/Manager/ProcessManager.php#L145-L147

https://github.com/asyncphp/doorman/blob/cff6addf82e98ec926cfb0d7e1c7d9b6fa53d2f4/src/Manager/ProcessManager.php#L228-L230

**Comment by asgrim** [comment]
That's the spirit! :)
