### ISSUE TITLE
5.3 support

### ISSUE THREAD

**Issue by mngreece** [asyncphp/doorman#14]
We noticed that ProcessManager.php calls the array_column function which is not supported in PHP 5.3 - however your documentation states the 1.X branch supports PHP 5.3 and above.

Please update documentation or add support for 5.3.

**Comment by assertchris** [comment]
The 1.x version requires an [`array_column` shim](https://github.com/asyncphp/doorman/blob/0da7eabebeae503fc05e90acaed021c692fceb57/composer.json#L7).
